name: build-front.yml

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/web/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'apps/web/**'

jobs:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write
  steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Upload server artifact"
      uses: docker/build-push-action@v6
      with:
        context: ./apps/web
        file: Dockerfile
        push: true
        tags: ghcr.io/opensource-together/front:latest
