name: Générer Swagger Doc

on:
  push:
    branches:
      - main

jobs:
  generate-swagger:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Copier le .env
        run: cp apps/server/.env.example apps/server/.env

      - name: Générer le client Prisma
        run: pnpm prisma generate

      - name: Lancer docker-compose
        run: docker compose -f apps/docker-compose.dev.yml up --build -d

      - name: Attendre que le backend soit prêt
        run: npx wait-on http://localhost:3000/api-json

      - name: Générer le swagger-doc.json
        run: curl http://localhost:3000/api-json > swagger-doc.json

      - name: Upload Swagger doc
        uses: actions/upload-artifact@v4
        with:
          name: swagger-doc
          path: swagger-doc.json
